org: juanrodo
service: sync-elasticsearch

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::735395269158:role/LabRole
  environment:
    TABLE_ORG: ${sls:stage}-t_org
    BUCKET_COMPRAS: datascience-compras-pruebas-${sls:stage}

resources:
  Resources:
    ComprasBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: datascience-compras-pruebas-${sls:stage}

functions:
  procesarCursosStream:
    handler: cursoStream.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::ImportValue: api-curso-${sls:stage}-CursoStreamArn
          batchSize: 5
          startingPosition: LATEST

  procesarHorariosStream:
    handler: horarioStream.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::ImportValue: api-horario-${sls:stage}-HorarioStreamArn
          batchSize: 5
          startingPosition: LATEST

  procesarComprasStream:
    handler: compraStream.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::ImportValue: api-compras-${sls:stage}-CompraStreamArn
          batchSize: 5
          startingPosition: LATEST

package:
  individually: false
  include:
    - '**'
